name: Pytest

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
 
      - name: Install apt package
        run: |
          sudo apt-get install -y --no-install-recommends \
          ifupdown \
          iproute2 \
          iptables \
          traceroute \
          curl \
          dnsutils \
          netcat-openbsd \
          openssh-client \
          iputils-ping \
          net-tools \
          bridge-utils \
          tcpdump \
          build-essential \
          libpcap-dev \
          libbsd-dev \
          dnsmasq \
          isc-dhcp-client \
          openvswitch-switch \
          git-core
          sudo touch /etc/network/interfaces
          sudo mkdir -p /opt/mininet_dependencies

      - name: Build mimidump
        run: |
          git clone https://github.com/mimi-net/mimidump.git
          cd mimidump && sudo make prefix=/usr install

      - name: Disable packet transmission to filters
        run: |
          sudo modprobe br_netfilter
          sudo sysctl -w net.bridge.bridge-nf-call-iptables=0
          sudo sysctl -w net.bridge.bridge-nf-call-arptables=0
          sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0
          sudo sysctl -p

      - name: Run Open VSwitch
        run: |
          sudo /usr/share/openvswitch/scripts/ovs-ctl start
          sudo ovs-vswitchd &

      - name: Test with pytest
        run: |
          sudo bash -c '
            python -m pip install --upgrade pip uv
            uv sync --all-groups
            cd back/tests
            export PYTHONPATH=$PYTHONPATH:../src
            uv run pytest .
          '