name: Linter

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Python (via uv)
        run: |
          python -V
          python -m pip install -U pip uv wheel setuptools
            
      - name: Install dependencies
        run: |                    
          uv sync --all-groups
          
      - name: Run all linters and fail if any detect issues
        run: |
          LINT_FAILED=false
          uv run mypy --install-types --non-interactive . || LINT_FAILED=true
          uv run mypy --ignore-missing-imports . || LINT_FAILED=true
          uv run isort --check-only --diff . || LINT_FAILED=true
          uv run black --check --verbose --diff . || LINT_FAILED=true
          uv run flake8 --count --verbose --max-line-length=88 --extend-ignore=E501,W391,C901,E203 --statistics . || LINT_FAILED=true
          uv run pylint --disable=R,C --max-line-length=88 . || LINT_FAILED=true
          if [ "$LINT_FAILED" = true ]; then
            echo "One or more linters failed."
            exit 1
          fi

      - name: Filter for Dockerfile changes
        id: docker_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dockerfiles:
              - '**/Dockerfile*'

      - name: Lint Dockerfile(s)
        if: steps.docker_filter.outputs.dockerfiles == 'true'
        uses: hadolint/hadolint-action@v3.3.0
        with:
          recursive: true
          no-fail: true
